const shoes = [
  {
    brand: "VANS",
    name: "Wearallday Shoes",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "VANS-001",
    price: 99.95,
    forMale: true,
    forFemale: true,
    newlyLaunched: true,
    onDiscount: true,
    discountPrice: null,
    discountPercent: 10,
    imagePath: "product_1.jpg",
  },
  {
    brand: "Nike",
    name: "Nike Sports",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "Nike-001",
    price: 129.95,
    forMale: true,
    forFemale: false,
    newlyLaunched: false,
    onDiscount: false,
    discountPrice: null,
    discountPercent: null,
    imagePath: "product_2.jpg",
  },
  {
    brand: "Adidas",
    name: "White Comfort",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "Adidas-001",
    price: 99.95,
    forMale: false,
    forFemale: true,
    newlyLaunched: true,
    onDiscount: false,
    discountPrice: null,
    discountPercent: null,
    imagePath: "product_3.jpg",
  },
  {
    brand: "VANS",
    name: "Converse Canvas",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "VANS-002",
    price: 84.95,
    forMale: true,
    forFemale: true,
    newlyLaunched: false,
    onDiscount: false,
    discountPrice: null,
    discountPercent: null,
    imagePath: "product_4.jpg",
  },
  {
    brand: "Nike",
    name: "Cool Sneakers",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "Nike-002",
    price: 99.95,
    forMale: true,
    forFemale: false,
    newlyLaunched: false,
    onDiscount: false,
    discountPrice: null,
    discountPercent: null,
    imagePath: "product_5.jpg",
  },
  {
    brand: "Nike",
    name: "Cool Sneakers",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "Nike-003",
    price: 140.95,
    forMale: false,
    forFemale: true,
    newlyLaunched: true,
    onDiscount: true,
    discountPrice: null,
    discountPercent: 12,
    imagePath: "product_6.jpg",
  },
  {
    brand: "Adidas",
    name: "Wearallday Shoes",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "CJ1682-004",
    price: 99.95,
    forMale: true,
    forFemale: false,
    newlyLaunched: true,
    onDiscount: false,
    discountPrice: null,
    discountPercent: null,
    imagePath: "product_7.jpg",
  },
  {
    brand: "Nike",
    name: "Green Walk",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "Nike-005",
    price: 140.95,
    forMale: true,
    forFemale: true,
    newlyLaunched: true,
    onDiscount: true,
    discountPrice: 110.95,
    discountPercent: null,
    imagePath: "product_8.jpg",
  },
  {
    brand: "Adidas",
    name: "White Bliss",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "Adidas-004",
    price: 99.95,
    forMale: true,
    forFemale: false,
    newlyLaunched: true,
    onDiscount: false,
    discountPrice: null,
    discountPercent: null,
    imagePath: "product_9.jpg",
  },
  {
    brand: "VANS",
    name: "Wearallday Shoes",
    desc: "Wearallday features plush padding around the ankle, a thick, downy tongue and unbelievably soft foam underfoot",
    code: "VANS-005",
    price: 124.95,
    forMale: true,
    forFemale: true,
    newlyLaunched: true,
    onDiscount: false,
    discountPrice: null,
    discountPercent: null,
    imagePath: "product_10.jpg",
  },
];

module.exports = Object.freeze(shoes);
